name: Java CI
on:
  push:
    branches:
      - main
    paths:
      - 'java/**'
      - '.github/workflows/ci_java.yml'
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/ci_java.yml'
  merge_group:
    paths:
      - 'java/**'
      - '.github/workflows/ci_java.yml'

permissions: write-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test (java/${{ matrix.sub-module }} ${{ matrix.java-version }} on ${{ matrix.os-label }})
    strategy:
      fail-fast: false
      matrix:
        sub-module: [ "device-oauth", "jwt-oauth", "pkce-oauth", "web-oauth" ]
        java-version: [ "8", "11", "17"]
        os: [ "ubuntu-latest" ]
        os-label: [ "Ubuntu" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Check & Build
        run: |
          cd "java/${{ matrix.sub-module }}"
          ./gradlew spotlessCheck
          ./gradlew checkstyleMain
          ./gradlew build
